const cardsInfoList = [
  [
    'Action (set A)',
    'Action (set B)',
    'Animal (set A)',
    'Nature',
    'Animal (set B)',
    'Clothes',
    'Food (set A)',
    'Food (set B)',
    'Emotions',
    'Body',
  ],
  [
    'Action (set A)',
    {
      word: 'cry',
      translation: 'плакать',
      image: './images/cry.jpg',
      audioSrc: './audio/cry.mp3',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: './images/dance.jpg',
      audioSrc: './audio/dance.mp3',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: './images/dive.jpg',
      audioSrc: './audio/dive.mp3',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: './images/draw.jpg',
      audioSrc: './audio/draw.mp3',
    },
    {
      word: 'fish (action)',
      translation: 'ловить рыбу',
      image: './images/fish (action).jpg',
      audioSrc: './audio/fish (action).mp3',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: './images/fly.jpg',
      audioSrc: './audio/fly.mp3',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: './images/hug.jpg',
      audioSrc: './audio/hug.mp3',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: './images/jump.jpg',
      audioSrc: './audio/jump.mp3',
    },
  ],
  [
    'Action (set B)',
    {
      word: 'open',
      translation: 'открывать',
      image: './images/open.jpg',
      audioSrc: './audio/open.mp3',
    },
    {
      word: 'play',
      translation: 'играть',
      image: './images/play.jpg',
      audioSrc: './audio/play.mp3',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: './images/point.jpg',
      audioSrc: './audio/point.mp3',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: './images/ride.jpg',
      audioSrc: './audio/ride.mp3',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: './images/run.jpg',
      audioSrc: './audio/run.mp3',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: './images/sing.jpg',
      audioSrc: './audio/sing.mp3',
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: './images/skip.jpg',
      audioSrc: './audio/skip.mp3',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: './images/swim.jpg',
      audioSrc: './audio/swim.mp3',
    },
  ],
  [
    'Animal (set A)',
    {
      word: 'cat',
      translation: 'кот',
      image: './images/cat.jpg',
      audioSrc: './audio/cat.mp3',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: './images/chick.jpg',
      audioSrc: './audio/chick.mp3',
    },
    {
      word: 'chicken (animal)',
      translation: 'курица',
      image: './images/chicken (animal).jpg',
      audioSrc: './audio/chicken (animal).mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: './images/dog.jpg',
      audioSrc: './audio/dog.mp3',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: './images/horse.jpg',
      audioSrc: './audio/horse.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: './images/pig.jpg',
      audioSrc: './audio/pig.mp3',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: './images/rabbit.jpg',
      audioSrc: './audio/rabbit.mp3',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: './images/sheep.jpg',
      audioSrc: './audio/sheep.mp3',
    },
  ],
  [
    'Nature',
    {
      word: 'sun',
      translation: 'солнце',
      image: './images/sun.jpg',
      audioSrc: './audio/sun.mp3',
    },
    {
      word: 'moon',
      translation: 'луна',
      image: './images/moon.jpg',
      audioSrc: './audio/moon.mp3',
    },
    {
      word: 'sky',
      translation: 'небо',
      image: './images/sky.jpg',
      audioSrc: './audio/sky.mp3',
    },
    {
      word: 'tree',
      translation: 'дерево',
      image: './images/tree.jpg',
      audioSrc: './audio/tree.mp3',
    },
    {
      word: 'earth',
      translation: 'Земля',
      image: './images/earth.png',
      audioSrc: './audio/earth.mp3',
    },
    {
      word: 'forest',
      translation: 'лес',
      image: './images/forest.jpg',
      audioSrc: './audio/forest.mp3',
    },
    {
      word: 'flower',
      translation: 'цветок',
      image: './images/flower.jpg',
      audioSrc: './audio/flower.mp3',
    },
    {
      word: 'grass',
      translation: 'трава',
      image: './images/grass1.png',
      audioSrc: './audio/grass.mp3',
    },
  ],
  [
    'Animal (set B)',
    {
      word: 'bird',
      translation: 'птица',
      image: './images/bird.jpg',
      audioSrc: './audio/bird.mp3',
    },
    {
      word: 'fish (animal)',
      translation: 'рыба',
      image: './images/fish (animal).jpg',
      audioSrc: './audio/fish (animal).mp3',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: './images/frog.jpg',
      audioSrc: './audio/frog.mp3',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: './images/giraffe.jpg',
      audioSrc: './audio/giraffe.mp3',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: './images/lion.jpg',
      audioSrc: './audio/lion.mp3',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: './images/mouse.jpg',
      audioSrc: './audio/mouse.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: './images/turtle.jpg',
      audioSrc: './audio/turtle.mp3',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: './images/dolphin.jpg',
      audioSrc: './audio/dolphin.mp3',
    },
  ],
  [
    'Clothes',
    {
      word: 'skirt',
      translation: 'юбка',
      image: './images/skirt.jpg',
      audioSrc: './audio/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: './images/pants.jpg',
      audioSrc: './audio/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: './images/blouse.jpg',
      audioSrc: './audio/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: './images/dress.jpg',
      audioSrc: './audio/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: './images/boot.jpg',
      audioSrc: './audio/boot.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: './images/shirt.jpg',
      audioSrc: './audio/shirt.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: './images/coat.jpg',
      audioSrc: './audio/coat.mp3',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: './images/shoe.jpg',
      audioSrc: './audio/shoe.mp3',
    },
  ],
  [
    'Food (set A)',
    {
      word: 'tomato',
      translation: 'помидор',
      image: './images/tomato.jpg',
      audioSrc: './audio/tomato.mp3',
    },
    {
      word: 'orange',
      translation: 'апельсин',
      image: './images/orange.png',
      audioSrc: './audio/orange.mp3',
    },
    {
      word: 'carrot',
      translation: 'морковь',
      image: './images/carrot.jpg',
      audioSrc: './audio/carrot.mp3',
    },
    {
      word: 'banana',
      translation: 'банан',
      image: './images/banana.jpg',
      audioSrc: './audio/banana.mp3',
    },
    {
      word: 'onion',
      translation: 'лук',
      image: './images/onion.jpg',
      audioSrc: './audio/onion.mp3',
    },
    {
      word: 'potato',
      translation: 'картофель',
      image: './images/potato.jpg',
      audioSrc: './audio/potato.mp3',
    },
    {
      word: 'cherry',
      translation: 'вишня',
      image: './images/cherry.jpg',
      audioSrc: './audio/cherry.mp3',
    },
    {
      word: 'apple',
      translation: 'яблоко',
      image: './images/apple.jpg',
      audioSrc: './audio/apple.mp3',
    },
  ],
  [
    'Food (set B)',
    {
      word: 'meat',
      translation: 'мясо',
      image: './images/meat.jpg',
      audioSrc: './audio/meat.mp3',
    },
    {
      word: 'sausage',
      translation: 'сосиска',
      image: './images/sausage.jpg',
      audioSrc: './audio/sausage.mp3',
    },
    {
      word: 'bread',
      translation: 'хлеб',
      image: './images/bread.jpg',
      audioSrc: './audio/bread.mp3',
    },
    {
      word: 'chicken (food)',
      translation: 'курица',
      image: './images/chicken (food).jpg ',
      audioSrc: './audio/chicken (food).mp3',
    },
    {
      word: 'cake',
      translation: 'торт',
      image: './images/cake.jpg',
      audioSrc: './audio/cake.mp3',
    },
    {
      word: 'soup',
      translation: 'суп',
      image: './images/soup.jpg',
      audioSrc: './audio/soup.mp3',
    },
    {
      word: 'porridge',
      translation: 'каша',
      image: './images/porridge.jpg',
      audioSrc: './audio/porridge.mp3',
    },
    {
      word: 'pasta',
      translation: 'макароны',
      image: './images/pasta.jpg',
      audioSrc: './audio/pasta.mp3',
    },
  ],
  [
    'Emotions',
    {
      word: 'sad',
      translation: 'грустный',
      image: './images/sad.jpg',
      audioSrc: './audio/sad.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: './images/angry.jpg',
      audioSrc: './audio/angry.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: './images/happy.jpg',
      audioSrc: './audio/happy.mp3',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: './images/tired.jpg',
      audioSrc: './audio/tired.mp3',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: './images/surprised.jpg',
      audioSrc: './audio/surprised.mp3',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: './images/scared.jpg',
      audioSrc: './audio/scared.mp3',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: './images/smile.jpg',
      audioSrc: './audio/smile.mp3',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: './images/laugh.jpg',
      audioSrc: './audio/laugh.mp3',
    },
  ],
  [
    'Body',
    {
      word: 'nose',
      translation: 'нос',
      image: './images/nose.jpg',
      audioSrc: './audio/nose.mp3',
    },
    {
      word: 'eye',
      translation: 'глаз',
      image: './images/eye.jpg',
      audioSrc: './audio/eye.mp3',
    },
    {
      word: 'ear',
      translation: 'ухо',
      image: './images/ear.jpg',
      audioSrc: './audio/ear.mp3',
    },
    {
      word: 'mouth',
      translation: 'рот',
      image: './images/mouth.jpg',
      audioSrc: './audio/mouth.mp3',
    },
    {
      word: 'hand',
      translation: 'рука',
      image: './images/hand.jpg',
      audioSrc: './audio/hand.mp3',
    },
    {
      word: 'head',
      translation: 'голова',
      image: './images/head.jpg',
      audioSrc: './audio/head.mp3',
    },
    {
      word: 'leg',
      translation: 'нога',
      image: './images/leg.jpg',
      audioSrc: './audio/leg.mp3',
    },
    {
      word: 'stomach',
      translation: 'живот',
      image: './images/stomach.jpg',
      audioSrc: './audio/stomach.mp3',
    },
  ],
];

export default cardsInfoList;
