const cardsInfoList = [
  [
    'Action (set A)',
    'Action (set B)',
    'Animal (set A)',
    'Nature',
    'Animal (set B)',
    'Clothes',
    'Food (set A)',
    'Food (set B)',
    'Emotions',
    'Body',
  ],
  [
    'Action (set A)',
    {
      word: 'cry',
      translation: 'плакать',
      image: '../public/img/cry.jpg',
      audioSrc: '../public/audio/cry.mp3',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: '../public/img/dance.jpg',
      audioSrc: '../public/audio/dance.mp3',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: '../public/img/dive.jpg',
      audioSrc: '../public/audio/dive.mp3',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: '../public/img/draw.jpg',
      audioSrc: '../public/audio/draw.mp3',
    },
    {
      word: 'fish (action)',
      translation: 'ловить рыбу',
      image: '../public/img/fish (action).jpg',
      audioSrc: '../public/audio/fish (action).mp3',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: '../public/img/fly.jpg',
      audioSrc: '../public/audio/fly.mp3',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: '../public/img/hug.jpg',
      audioSrc: '../public/audio/hug.mp3',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: '../public/img/jump.jpg',
      audioSrc: '../public/audio/jump.mp3',
    },
  ],
  [
    'Action (set B)',
    {
      word: 'open',
      translation: 'открывать',
      image: '../public/img/open.jpg',
      audioSrc: '../public/audio/open.mp3',
    },
    {
      word: 'play',
      translation: 'играть',
      image: '../public/img/play.jpg',
      audioSrc: '../public/audio/play.mp3',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: '../public/img/point.jpg',
      audioSrc: '../public/audio/point.mp3',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: '../public/img/ride.jpg',
      audioSrc: '../public/audio/ride.mp3',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: '../public/img/run.jpg',
      audioSrc: '../public/audio/run.mp3',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: '../public/img/sing.jpg',
      audioSrc: '../public/audio/sing.mp3',
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: '../public/img/skip.jpg',
      audioSrc: '../public/audio/skip.mp3',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: '../public/img/swim.jpg',
      audioSrc: '../public/audio/swim.mp3',
    },
  ],
  [
    'Animal (set A)',
    {
      word: 'cat',
      translation: 'кот',
      image: '../public/img/cat.jpg',
      audioSrc: '../public/audio/cat.mp3',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: '../public/img/chick.jpg',
      audioSrc: '../public/audio/chick.mp3',
    },
    {
      word: 'chicken (animal)',
      translation: 'курица',
      image: '../public/img/chicken (animal).jpg',
      audioSrc: '../public/audio/chicken (animal).mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: '../public/img/dog.jpg',
      audioSrc: '../public/audio/dog.mp3',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: '../public/img/horse.jpg',
      audioSrc: '../public/audio/horse.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: '../public/img/pig.jpg',
      audioSrc: '../public/audio/pig.mp3',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: '../public/img/rabbit.jpg',
      audioSrc: '../public/audio/rabbit.mp3',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: '../public/img/sheep.jpg',
      audioSrc: '../public/audio/sheep.mp3',
    },
  ],
  [
    'Nature',
    {
      word: 'sun',
      translation: 'солнце',
      image: '../public/img/sun.jpg',
      audioSrc: '../public/audio/sun.mp3',
    },
    {
      word: 'moon',
      translation: 'луна',
      image: '../public/img/moon.jpg',
      audioSrc: '../public/audio/moon.mp3',
    },
    {
      word: 'sky',
      translation: 'небо',
      image: '../public/img/sky.jpg',
      audioSrc: '../public/audio/sky.mp3',
    },
    {
      word: 'tree',
      translation: 'дерево',
      image: '../public/img/tree.jpg',
      audioSrc: '../public/audio/tree.mp3',
    },
    {
      word: 'earth',
      translation: 'Земля',
      image: '../public/img/earth.png',
      audioSrc: '../public/audio/earth.mp3',
    },
    {
      word: 'forest',
      translation: 'лес',
      image: '../public/img/forest.jpg',
      audioSrc: '../public/audio/forest.mp3',
    },
    {
      word: 'flower',
      translation: 'цветок',
      image: '../public/img/flower.jpeg',
      audioSrc: '../public/audio/flower.mp3',
    },
    {
      word: 'grass',
      translation: 'трава',
      image: '../public/img/grass1.png',
      audioSrc: '../public/audio/grass.mp3',
    },
  ],
  [
    'Animal (set B)',
    {
      word: 'bird',
      translation: 'птица',
      image: '../public/img/bird.jpg',
      audioSrc: '../public/audio/bird.mp3',
    },
    {
      word: 'fish (animal)',
      translation: 'рыба',
      image: '../public/img/fish (animal).jpg',
      audioSrc: '../public/audio/fish (animal).mp3',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: '../public/img/frog.jpg',
      audioSrc: '../public/audio/frog.mp3',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: '../public/img/giraffe.jpg',
      audioSrc: '../public/audio/giraffe.mp3',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: '../public/img/lion.jpg',
      audioSrc: '../public/audio/lion.mp3',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: '../public/img/mouse.jpg',
      audioSrc: '../public/audio/mouse.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: '../public/img/turtle.jpg',
      audioSrc: '../public/audio/turtle.mp3',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: '../public/img/dolphin.jpg',
      audioSrc: '../public/audio/dolphin.mp3',
    },
  ],
  [
    'Clothes',
    {
      word: 'skirt',
      translation: 'юбка',
      image: '../public/img/skirt.jpg',
      audioSrc: '../public/audio/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: '../public/img/pants.jpg',
      audioSrc: '../public/audio/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: '../public/img/blouse.jpg',
      audioSrc: '../public/audio/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: '../public/img/dress.jpg',
      audioSrc: '../public/audio/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: '../public/img/boot.jpg',
      audioSrc: '../public/audio/boot.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: '../public/img/shirt.jpg',
      audioSrc: '../public/audio/shirt.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: '../public/img/coat.jpg',
      audioSrc: '../public/audio/coat.mp3',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: '../public/img/shoe.jpg',
      audioSrc: '../public/audio/shoe.mp3',
    },
  ],
  [
    'Food (set A)',
    {
      word: 'tomato',
      translation: 'помидор',
      image: '../public/img/tomato.jpg',
      audioSrc: '../public/audio/tomato.mp3',
    },
    {
      word: 'orange',
      translation: 'апельсин',
      image: '../public/img/orange.png',
      audioSrc: '../public/audio/orange.mp3',
    },
    {
      word: 'carrot',
      translation: 'морковь',
      image: '../public/img/carrot.jpg',
      audioSrc: '../public/audio/carrot.mp3',
    },
    {
      word: 'banana',
      translation: 'банан',
      image: '../public/img/banana.jpg',
      audioSrc: '../public/audio/banana.mp3',
    },
    {
      word: 'onion',
      translation: 'лук',
      image: '../public/img/onion.jpg',
      audioSrc: '../public/audio/onion.mp3',
    },
    {
      word: 'potato',
      translation: 'картофель',
      image: '../public/img/potato.jpg',
      audioSrc: '../public/audio/potato.mp3',
    },
    {
      word: 'cherry',
      translation: 'вишня',
      image: '../public/img/cherry.jpg',
      audioSrc: '../public/audio/cherry.mp3',
    },
    {
      word: 'apple',
      translation: 'яблоко',
      image: '../public/img/apple.jpg',
      audioSrc: '../public/audio/apple.mp3',
    },
  ],
  [
    'Food (set B)',
    {
      word: 'meat',
      translation: 'мясо',
      image: '../public/img/meat.jpg',
      audioSrc: '../public/audio/meat.mp3',
    },
    {
      word: 'sausage',
      translation: 'сосиска',
      image: '../public/img/sausage.jpg',
      audioSrc: '../public/audio/sausage.mp3',
    },
    {
      word: 'bread',
      translation: 'хлеб',
      image: '../public/img/bread.jpg',
      audioSrc: '../public/audio/bread.mp3',
    },
    {
      word: 'chicken (food)',
      translation: 'курица',
      image: '../public/img/chicken (food).jpg ',
      audioSrc: '../public/audio/chicken (food).mp3',
    },
    {
      word: 'cake',
      translation: 'торт',
      image: '../public/img/cake.jpg',
      audioSrc: '../public/audio/cake.mp3',
    },
    {
      word: 'soup',
      translation: 'суп',
      image: '../public/img/soup.jpg',
      audioSrc: '../public/audio/soup.mp3',
    },
    {
      word: 'porridge',
      translation: 'каша',
      image: '../public/img/porridge.jpeg',
      audioSrc: '../public/audio/porridge.mp3',
    },
    {
      word: 'pasta',
      translation: 'макароны',
      image: '../public/img/pasta.jpg',
      audioSrc: '../public/audio/pasta.mp3',
    },
  ],
  [
    'Emotions',
    {
      word: 'sad',
      translation: 'грустный',
      image: '../public/img/sad.jpg',
      audioSrc: '../public/audio/sad.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: '../public/img/angry.jpg',
      audioSrc: '../public/audio/angry.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: '../public/img/happy.jpg',
      audioSrc: '../public/audio/happy.mp3',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: '../public/img/tired.jpg',
      audioSrc: '../public/audio/tired.mp3',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: '../public/img/surprised.jpg',
      audioSrc: '../public/audio/surprised.mp3',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: '../public/img/scared.jpg',
      audioSrc: '../public/audio/scared.mp3',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: '../public/img/smile.jpg',
      audioSrc: '../public/audio/smile.mp3',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: '../public/img/laugh.jpg',
      audioSrc: '../public/audio/laugh.mp3',
    },
  ],
  [
    'Body',
    {
      word: 'nose',
      translation: 'нос',
      image: '../public/img/nose.jpg',
      audioSrc: '../public/audio/nose.mp3',
    },
    {
      word: 'eye',
      translation: 'глаз',
      image: '../public/img/eye.jpg',
      audioSrc: '../public/audio/eye.mp3',
    },
    {
      word: 'ear',
      translation: 'ухо',
      image: '../public/img/ear.jpg',
      audioSrc: '../public/audio/ear.mp3',
    },
    {
      word: 'mouth',
      translation: 'рот',
      image: '../public/img/mouth.jpg',
      audioSrc: '../public/audio/mouth.mp3',
    },
    {
      word: 'hand',
      translation: 'рука',
      image: '../public/img/hand.jpg',
      audioSrc: '../public/audio/hand.mp3',
    },
    {
      word: 'head',
      translation: 'голова',
      image: '../public/img/head.jpg',
      audioSrc: '../public/audio/head.mp3',
    },
    {
      word: 'leg',
      translation: 'нога',
      image: '../public/img/leg.jpg',
      audioSrc: '../public/audio/leg.mp3',
    },
    {
      word: 'stomach',
      translation: 'живот',
      image: '../public/img/stomach.jpg',
      audioSrc: '../public/audio/stomach.mp3',
    },
  ],
];

export default cardsInfoList;
